package com.meimei.newstudent.view.Fragment.StrategyFragment;

import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import com.meimei.newstudent.R;
import com.meimei.newstudent.adapter.Rv_Adapter_Surrounding;
import com.meimei.newstudent.bean.Surrounding;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by 梅梅 on 2016/8/4.
 */
public class Food_Fragment extends Fragment{
    private static String TAG = "Food_Fragment";
    private View view;
    private RecyclerView recyclerView;
    private Rv_Adapter_Surrounding rv_adapter_surrounding;
    private List<Surrounding> data = new ArrayList<>();
    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {

        Log.i(TAG,"onCreateView");
        view = inflater.inflate(R.layout.fragment_strategy_food,container,false);
        init();
        //拿数据
        if (data.size() == 0){
            getData();
        }
        rv_adapter_surrounding = new Rv_Adapter_Surrounding(R.layout.rv_surrounding_item,getActivity(),data);
        recyclerView.setAdapter(rv_adapter_surrounding);
        return view;
    }

    private void init(){
        recyclerView = (RecyclerView) view.findViewById(R.id.rv_food);
        recyclerView.setLayoutManager(new LinearLayoutManager(getActivity()));

    }
    private void getData(){
        Surrounding item = new Surrounding();
        item.setName("老寨火锅");
        item.setLocation("老校门对面堕落街");
        item.setIntroduction("好吃不上火，价格公道");
        data.add(item);
        Surrounding item1 = new Surrounding();
        item1.setName("吹2锅荷叶木桶饭");
        item1.setLocation("老校门对面堕落街");
        item1.setIntroduction("清香味美，物美价廉");
        data.add(item1);
        Surrounding item2 = new Surrounding();
        item2.setName("尝香思铁板烧");
        item2.setLocation("老校门对面堕落街");
        item2.setIntroduction("独具特色，回味悠长");
        data.add(item2);
        Surrounding item3 = new Surrounding();
        item3.setName("三顾冒菜");
        item3.setLocation("地址：老校门对面堕落街");
        item3.setIntroduction("爽口回味，好吃不贵");
        data.add(item3);
        Surrounding item4 = new Surrounding();
        item4.setName("重庆鸡公煲");
        item4.setLocation("老校门对面堕落街");
        item4.setIntroduction("好吃不辣，量足管饱");
        data.add(item4);
        Surrounding item5 = new Surrounding();
        item5.setName("新疆沙湾大盘鸡");
        item5.setLocation("老校门对面堕落街");
        item5.setIntroduction("独具疆域特色");
        data.add(item5);
        Surrounding item6 = new Surrounding();
        item6.setName("福宇记黄焖鸡");
        item6.setLocation("老校门对面堕落街");
        item6.setIntroduction("香味浓郁");
        data.add(item6);
        Surrounding item7 = new Surrounding();
        item7.setName("撒拉尔牛肉面");
        item7.setLocation("老校门对面堕落街");
        item7.setIntroduction("独具清真特色");
        data.add(item7);
        Surrounding item8 = new Surrounding();
        item8.setName("渝香铁板烧");
        item8.setLocation("老校门对面堕落街");
        item8.setIntroduction("味道纯正，香气十足");
        data.add(item8);
        Surrounding item9 = new Surrounding();
        item9.setName("刘氏鸡公煲");
        item9.setLocation("老校门对面堕落街");
        item9.setIntroduction("浓香滑嫩，入味彻底");
        data.add(item9);
        Surrounding item10 = new Surrounding();
        item10.setName("阿里郎");
        item10.setLocation("老校门对面堕落街");
        item10.setIntroduction("独具台式风味");
        data.add(item10);
        Surrounding item11 = new Surrounding();
        item11.setName("陈记干锅");
        item11.setLocation("老校门对面堕落街");
        item11.setIntroduction("量大分足，赏心悦目");
        data.add(item11);
        Surrounding item12 = new Surrounding();
        item12.setName("李海粥王");
        item12.setLocation("老校门对面堕落街");
        item12.setIntroduction("营养美味");
        data.add(item12);
        Surrounding item13 = new Surrounding();
        item13.setName("旮旯酸辣粉、羊肉粉");
        item13.setLocation("老校门对面堕落街");
        item13.setIntroduction("回味悠长，麻辣鲜香");
        data.add(item13);
        Surrounding item14 = new Surrounding();
        item14.setName("熙熙冒菜");
        item14.setLocation("老校门对面堕落街");
        item14.setIntroduction("麻辣鲜香");
        data.add(item14);
        Surrounding item15 = new Surrounding();
        item15.setName("三番料理");
        item15.setLocation("老校门对面堕落街");
        item15.setIntroduction("唇齿留香，色味俱佳");
        data.add(item15);
        Surrounding item16 = new Surrounding();
        item16.setName("好又来");
        item16.setLocation("老校门对面堕落街");
        item16.setIntroduction("好吃不贵");
        data.add(item16);
        Surrounding item17 = new Surrounding();
        item17.setName("咖喱至尊");
        item17.setLocation("老校门对面堕落街");
        item17.setIntroduction("色香味美，物美价廉");
        data.add(item17);
        Surrounding item18 = new Surrounding();
        item18.setName("边林社");
        item18.setLocation("老校门对面堕落街");
        item18.setIntroduction("美味佳肴");
        data.add(item18);
        Surrounding item19 = new Surrounding();
        item19.setName("小酒馆");
        item19.setLocation("老校门对面堕落街");
        item19.setIntroduction("文青聚集地");
        data.add(item19);
        Surrounding item20 = new Surrounding();
        item20.setName("馄钝王");
        item20.setLocation("老校门对面堕落街");
        item20.setIntroduction("皮薄馅多");
        data.add(item20);
        Surrounding item21 = new Surrounding();
        item21.setName("嬢嬢汤圆");
        item21.setLocation("老校门对面堕落街");
        item21.setIntroduction("嬢嬢好，汤圆妈妈味");
        data.add(item21);
        Surrounding item22 = new Surrounding();
        item22.setName("李记串串");
        item22.setLocation("永辉超市旁边");
        item22.setIntroduction("口味独特，麻辣鲜香");
        data.add(item22);
        Surrounding item23 = new Surrounding();
        item23.setName("纸包鱼");
        item23.setLocation("新校门对面罐罐米线旁边");
        item23.setIntroduction("味美可口");
        data.add(item23);
        Surrounding item24 = new Surrounding();
        item24.setName("豆花鱼");
        item24.setLocation("新校门对面堕落街2街第一家");
        item24.setIntroduction("豆浆涮鱼好滋味。（ps:他家豆花是免费吃的哦~）");
        data.add(item24);
        Surrounding item25 = new Surrounding();
        item25.setName("万州巴斗香烤鱼");
        item25.setLocation("新校门出门右转，农业银行旁买水果的巷子里面");
        item25.setIntroduction("口味奇绝、营养丰富");
        data.add(item25);
        Surrounding item26 = new Surrounding();
        item26.setName("蜜雪冰城");
        item26.setLocation("老校门对面");
        item26.setIntroduction("这家的冰激凌很好吃哦，有抹茶，原味和混合三种口味哦~而且不贵，只要两块，物美价廉！");
        data.add(item26);
        Surrounding item27 = new Surrounding();
        item27.setName("果然");
        item27.setLocation("老校门对面");
        item27.setIntroduction("满满一杯细细品味，哇噢!就是这个味道！");
        data.add(item27);
        Surrounding item28 = new Surrounding();
        item28.setName("城门老火锅");
        item28.setLocation("新校门出门，过马路右转下山的路边");
        item28.setIntroduction("辣而不燥，回味悠长");
        data.add(item28);
        Surrounding item29 = new Surrounding();
        item29.setName("Daydream");
        item29.setLocation("老校门出门过马路左转直走看见采蝶轩汤锅，就在它旁边（在角落，不是很好找）");
        item29.setIntroduction("环境优美，是一个文青们聚集，讲述故事的世外桃源");
        data.add(item29);
        Surrounding item30 = new Surrounding();
        item30.setName("华莱士");
        item30.setLocation("老校门对面");
        item30.setIntroduction("物美价廉，种类繁多，美味可口");
        data.add(item30);
        Surrounding item31 = new Surrounding();
        item31.setName("袁姐牛肉面");
        item31.setLocation("老校门对面");
        item31.setIntroduction("牛肉甘温、安中益气、养脾胃");
        data.add(item31);
        Surrounding item32 = new Surrounding();
        item32.setName("大茶杯");
        item32.setLocation("老校门对面");
        item32.setIntroduction("这里的招牌奶茶如丝般顺滑，奶香味十足");
        data.add(item32);
        Surrounding item33 = new Surrounding();
        item33.setName("彩蝶轩");
        item33.setLocation("老校门出门过马路左转一直走");
        item33.setIntroduction("这里的汤锅辣爽可口，自助烤肉趣味十足");
        data.add(item33);
        Surrounding item34 = new Surrounding();
        item34.setName("贵州蘸水米线");
        item34.setLocation("老校门出门过马路左转一直走");
        item34.setIntroduction("价格合理，汤浓鲜香");
        data.add(item34);
        Surrounding item35 = new Surrounding();
        item35.setName("罗非鱼");
        item35.setLocation("老校门出门过马路左转一直走，路边");
        item35.setIntroduction("肉味鲜美，肉质细嫩");
        data.add(item35);
        Surrounding item36 = new Surrounding();
        item36.setName("九村烤脑花");
        item36.setLocation("老校门出门过马路左转一直走，路边");
        item36.setIntroduction("气味醇厚，入口绵软，香而不腻，油而不肥");
        data.add(item36);
        Surrounding item37 = new Surrounding();
        item37.setName("杀牛王老火锅");
        item37.setLocation("老校门出门过马路左转一直走，路边");
        item37.setIntroduction("这里的汤锅辣爽可口，自助烤肉趣味十足");
        data.add(item37);
        Surrounding item38 = new Surrounding();
        item38.setName("毛哥老鸭汤");
        item38.setLocation("老校门出门过马路左转一直走，路边");
        item38.setIntroduction("汤老鸭（唐老鸭），有趣，简单，又不乏幽默。");
        data.add(item38);
        Surrounding item39 = new Surrounding();
        item39.setName("鹅掌老鸭汤");
        item39.setLocation("老校门出门过马路左转一直走，路边");
        item39.setIntroduction("地道重庆味");
        data.add(item39);
        Surrounding item40 = new Surrounding();
        item40.setName("田间烂鱼头");
        item40.setLocation("老校门出门过马路左转一直走，路边");
        item40.setIntroduction("鲜而不腥，入口窜香");
        data.add(item40);
        Surrounding item41 = new Surrounding();
        item41.setName("第一家火锅串串");
        item41.setLocation("老校门出门过马路左转一直走，路边（斜坡旁边）");
        item41.setIntroduction("第一家串串香，麻辣的亲密接触");
        data.add(item41);
        Surrounding item42 = new Surrounding();
        item42.setName("柒露营串串");
        item42.setLocation("老校门出门过马路左转，斜坡旁边巷子进去");
        item42.setIntroduction("柒露营，一家和重邮一起成长的老店");
        data.add(item42);
        Surrounding item43 = new Surrounding();
        item43.setName("无届青年餐馆");
        item43.setLocation("老校门出门过马路左转，斜坡旁边巷子进去，柒露营串串旁边");
        item43.setIntroduction("一个聚集大批文青谈人生聊梦想，以酒会友的地方");
        data.add(item43);
        Surrounding item44 = new Surrounding();
        item44.setName("东北饺子馆");
        item44.setLocation("老校门出门过马路左转，斜坡旁边巷子进去，柒露营串串1号店旁边");
        item44.setIntroduction("正如东北的豪放与热情，这里的饺子很大个哦~");
        data.add(item44);
        Surrounding item45 = new Surrounding();
        item45.setName("土巴碗");
        item45.setLocation("老校门对面左转斜坡上右边");
        item45.setIntroduction("里面有各种特色套饭，炒饭和面条抄手等");
        data.add(item45);
        Surrounding item46 = new Surrounding();
        item46.setName("隆江猪脚饭");
        item46.setLocation("老校门对面堕落街里面第一家");
        item46.setIntroduction("猪脚肥而不腻，入口即化");
        data.add(item46);
        Surrounding item47 = new Surrounding();
        item47.setName("净香园");
        item47.setLocation("老校门对面堕落街里");
        item47.setIntroduction("净香园饭店,人间舒适新享受");
        data.add(item47);
        Surrounding item48 = new Surrounding();
        item48.setName("黄焖鸡米饭");
        item48.setLocation("老校门对面");
        item48.setIntroduction("好吃，又实惠，配上米饭一吃，那就一个字 ，绝");
        data.add(item48);
        Surrounding item49 = new Surrounding();
        item49.setName("豆汤饭");
        item49.setLocation("老校门对面堕落街里");
        item49.setIntroduction("净香园饭店,人间舒适新享受");
        data.add(item49);
        Surrounding item50 = new Surrounding();
        item50.setName("沁源干锅");
        item50.setLocation("老校门对面堕落街里面");
        item50.setIntroduction("味美鲜香");
        data.add(item50);
        Surrounding item51 = new Surrounding();
        item51.setName("奈斯汉堡");
        item51.setLocation("老校门对面右转堕落2街里面");
        item51.setIntroduction("食欲大开");
        data.add(item51);
        Surrounding item52 = new Surrounding();
        item52.setName("彩蝶轩港式中西餐厅");
        item52.setLocation("老校门对面右转堕落2街里面");
        item52.setIntroduction("好味道，错过就是过错！注意哦，这不是外面的彩蝶轩汤锅，这里面也有套饭的哦~");
        data.add(item52);
        Surrounding item53 = new Surrounding();
        item53.setName("韩品屋");
        item53.setLocation("新校门对面堕落2街路口");
        item53.setIntroduction("一股韩国式的飘香味袭来");
        data.add(item53);
        Surrounding item54 = new Surrounding();
        item54.setName("燃面饺子馆");
        item54.setLocation("老校门堕落街里面");
        item54.setIntroduction("满口喷香，馅多汁多");
        data.add(item54);
        Surrounding item55 = new Surrounding();
        item55.setName("第一佳大鸡排");
        item55.setLocation("老校门对面右转直走路边");
        item55.setIntroduction("汁多肉嫩，皮脆香酥");
        data.add(item55);
        Surrounding item56 = new Surrounding();
        item56.setName("长生饺子馆");
        item56.setLocation("新校门对面堕落街里面");
        item56.setIntroduction("一对母子开的一家老店，饺子数量足，现包现煮");
        data.add(item56);
        Surrounding item57 = new Surrounding();
        item57.setName("东北麻辣拌");
        item57.setLocation("新校门对面堕落2街路口");
        item57.setIntroduction("一股韩国式的飘香味袭来");
        data.add(item57);
        Surrounding item58 = new Surrounding();
        item58.setName("肠鲜楼江湖菜");
        item58.setLocation("新校门对面广益中学路牌旁边");
        item58.setIntroduction("武侠餐饮，座座爆满");
        data.add(item58);
        Surrounding item59 = new Surrounding();
        item59.setName("创维江湖火山石烫鱼");
        item59.setLocation("新校门出门右转向下山方向一直走，在路边就可看见");
        item59.setIntroduction("一锅在手，温暖一冬");
        data.add(item59);
        Surrounding item60 = new Surrounding();
        item60.setName("重庆家福火锅");
        item60.setLocation("新校门出门左转即可看到");
        item60.setIntroduction("麻辣酸爽，飘香四溢");
        data.add(item60);
        Surrounding item61 = new Surrounding();
        item61.setName("沁园");
        item61.setLocation("老校门出门右转邮政旁边");
        item61.setIntroduction("甜香扑鼻，松软可口");
        data.add(item61);
        Surrounding item62 = new Surrounding();
        item62.setName("绝味鸭脖");
        item62.setLocation("老校门出门右转牛杂王旁边");
        item62.setIntroduction("鲜香麻辣，越啃越有味。");
        data.add(item62);




    }
}
